AWSTemplateFormatVersion: '2010-09-09'
Description: 'Skill Bridge Platform - AWS CloudFormation Stack'

Parameters:
  EnvironmentName:
    Description: Environment name prefix
    Type: String
    Default: SkillBridge

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Security Group
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP, HTTPS and SSH
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  SkillBridgeEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs nginx git
          npm install -g pm2
          git clone https://github.com/AdithNair03/skillbridge.git /home/ubuntu/skillbridge
          cd /home/ubuntu/skillbridge/backend
          npm install
          pm2 start server.js --name skillbridge
          pm2 startup && pm2 save

Outputs:
  PublicIP:
    Description: Public IP of Skill Bridge Server
    Value: !GetAtt SkillBridgeEC2.PublicIp
  AppURL:
    Description: URL to access Skill Bridge
    Value: !Sub http://${SkillBridgeEC2.PublicIp}
